apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
  namespace: weather-app
  labels:
    app: weather-frontend
spec:
  type: LoadBalancer
  selector:
    app: weather-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: None
